GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "Fajar Kresna Pahlawan"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id" : 0,
  "todo": "Programmer Ngaco"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id" : 0
}
